### ISSUE TITLE
Footnotes::Notes::ControllerNote Exception: can't convert nil into String on ActiveAdmin pages

### ISSUE THREAD

**Issue by styx** [indirect/rails-footnotes#69]
```
Started GET "/admin/login" for 127.0.0.1 at 2012-01-11 10:50:46 +0300
  Processing by ActiveAdmin::Devise::SessionsController#new as HTML
DEPRECATION WARNING: Formtastic::SemanticFormBuilder has been deprecated in favor of Formtastic::FormBuilder. (called from realtime at /home/user/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/benchmark.rb:295)
DEPRECATION WARNING: Formtastic::SemanticFormBuilder has been deprecated in favor of Formtastic::FormBuilder. (called from realtime at /home/user/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/benchmark.rb:295)
Rendered /home/user/.rvm/gems/ruby-1.9.3-p0/gems/devise-1.5.3/app/views/devise/shared/_links.erb (0.6ms)
Rendered /home/user/.rvm/gems/ruby-1.9.3-p0/gems/activeadmin-0.3.0/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out (20.4ms)
Footnotes Footnotes::Notes::ControllerNote Exception: can't convert nil into String
/home/user/.rvm/gems/ruby-1.9.3-p0/gems/rails-footnotes-3.7.5/lib/rails-footnotes/notes/controller_note.rb:17:in `exists?'
/home/user/.rvm/gems/ruby-1.9.3-p0/gems/rails-footnotes-3.7.5/lib/rails-footnotes/notes/controller_note.rb:17:in `valid?'
/home/user/.rvm/gems/ruby-1.9.3-p0/gems/rails-footnotes-3.7.5/lib/rails-footnotes/footnotes.rb:133:in `block in initialize_notes!'
/home/user/.rvm/gems/ruby-1.9.3-p0/gems/rails-footnotes-3.7.5/lib/rails-footnotes/footnotes.rb:62:in `block in each_with_rescue'
/home/user/.rvm/gems/ruby-1.9.3-p0/gems/rails-footnotes-3.7.5/lib/rails-footnotes/footnotes.rb:60:in `each'
/home/user/.rvm/gems/ruby-1.9.3-p0/gems/rails-footnotes-3.7.5/lib/rails-footnotes/footnotes.rb:60:in `each_with_rescue'
/home/user/.rvm/gems/ruby-1.9.3-p0/gems/rails-footnotes-3.7.5/lib/rails-footnotes/footnotes.rb:355:in `each_with_rescue'
/home/user/.rvm/gems/ruby-1.9.3-p0/gems/rails-footnotes-3.7.5/lib/rails-footnotes/footnotes.rb:131:in `initialize_notes!'
/home/user/.rvm/gems/ruby-1.9.3-p0/gems/rails-footnotes-3.7.5/lib/rails-footnotes/footnotes.rb:125:in `add_footnotes_without_validation!'
/home/user/.rvm/gems/ruby-1.9.3-p0/gems/rails-footnotes-3.7.5/lib/rails-footnotes/footnotes.rb:102:in `add_footnotes!'
/home/user/.rvm/gems/ruby-1.9.3-p0/gems/rails-footnotes-3.7.5/lib/rails-footnotes/footnotes.rb:14:in `filter'
```

**Comment by indirect** [comment]
Should be fixed in 7.0.0.
